/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import escuela.Escuela;
import estructural.ServicioEscuela;

/**
 *
 * @author Guilherme
 */
public class GUIListarEscuela extends javax.swing.JFrame implements IActualizableEscuela{
    
    ServicioEscuela ser;
    Escuela e;
    
    /**
     * Creates new form GUIListarEscuela
     */
    public GUIListarEscuela() { }
    public GUIListarEscuela(ServicioEscuela refSer) 
    {
        initComponents();
        this.ser = refSer;
        actualizable();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        voltar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEscuela = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        voltar.setText("<");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        tblEscuela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "Escuela", "Profesor", "Estudiante"
            }
        ));
        jScrollPane2.setViewportView(tblEscuela);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(voltar)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(voltar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_voltarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblEscuela;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actualizable() 
    {
       cargar();
        
    }
    public void cargar()
    {

        String m [][] = new String[(ser.getArrayEsc().size())] [4];
        for (int i = 0; i < ser.getArrayEsc().size(); i++) {
           //m[i][0] = Integer.toString(ser.getArrayEsc().get(i).getId());
           m[i][0] = ser.getArrayEsc().get(i).getIdE();
           m[i][1] = ser.getArrayEsc().get(i).getNombre();
           m[i][2] = ser.getArrayEsc().get(i).getProfesor();
           m[i][3] = ser.getArrayEsc().get(i).getEstudiante(); 
        }
        
        tblEscuela.setModel(new javax.swing.table.DefaultTableModel(
            m,
            new String [] {
                "id", "Escuela", "Profesor", "Estudiante"
            }
        ));
    }
    
}
